### ISSUE TITLE
Relative dates are not localized and ignore timezones (regression since IMP 6.2.27)

### ISSUE THREAD

**Issue by jcdelepine** [horde/imp#22]
In IMP 6.2.27 (Horde 5), the message date was shown as a plain absolute timestamp, properly localized and timezone-adjusted.

In IMP 7.0.0-alpha17 (Horde 6), message dates are now shown using relative time (e.g., “18 hours ago”) via time-elements.js. However, this implementation introduces two major issues:

1. Localization is broken
The relative labels (e.g., "yesterday", "18 hours ago") are always displayed in English, regardless of the user’s language settings. The strings are hardcoded and not integrated with gettext or any translation mechanism.

2. Timezone handling is incorrect
Time differences appear to be calculated assuming UTC for both dates, ignoring the user’s actual timezone setting. For example, when reading a message sent at 8:00 UTC from a client in UTC+2, the UI incorrectly displays "2 hours ago" instead of "now".

The feature seems to have been introduced in commit 85c6d6efaf5446a2e5bfa5df68ce4ad56d444774 using time-elements.js. There is no integration with gettext or timezone logic.

This is a regression in usability compared to Horde 5.

**Comment by ralflang** [comment]
Thank you for reporting. This should be fixed before production release.

**Comment by jcdelepine** [comment]
Some followup on this issue. 
1. Localization is still broken : 
   - Aujourd'hui, 09:35:21 CEST (35 minutes ago)
   - 11/06/2026 (03:37:00 CEST) (2 days ago)
2. Timezone handling is now correct

**Comment by ralflang** [comment]
@jcdelepine Please reopen if the latest commit does not solve it for you.
